@startuml

skinparam actorStyle Hollow
skinparam backgroundColor lightblue
skinparam shadowing false
skinparam noteBackgroundColor lightyellow

!pragma teoz true
!pragma sequenceMessageSpan true
skinparam ParticipantPadding 30

/'
* The tunnel can receive the same broadcast on many interfaces from the same NodeID.
*   We need to cache the TunnelGateway associated with the peer's NodeID
*   The TunnelGateway needs to cache the IP/port associated with the NodeID
*   We need to cache the last broadcast of a Node ID to avoid sending the same broadcast
multiple times.

* When the unique broadcast of a NodeID is received in the other side of the tunnel, 
*   it is forwarded to all TunnelGateways.
* Each TunnelGateway will create/update an Endpoint 
*   for the NodeID the broadcast came from.
* The broadcast will then be sent on all Endpoints.
*
* When a peer responds to the broadcast, it'll send an unicast to the specific Endpoint.
*   We need to cache the TunnelGateway associated with the peer's NodeID
*   The TunnelGateway needs to cache the IP/port associated with the NodeID
* The unicast will be received and sent to the other side of the tunnel,
*   where an Endpoint is created/updated for the Node ID of the peer on each interface.
* The unicast will then be forwarded to the known Peer interface/IP/port.
'/

/'
The 'measurements' have a timer of 50 milliseconds.
'/

actor AbletonLink1

AbletonLink1 -> LAN ++ : broadcast PeerState(NodeID1)
LAN -> TunnelGateway1 --++ : broadcast PeerState(NodeID1)

TunnelGateway1 -> TunnelGateway1 : store NodeID1 state & measurement UdpEndpoint
note right: an UdpEndpoint is the combination of IP+port
TunnelGateway1 -> TunnelGateway1 : remove measurement UdpEndpoint from PeerState message, leave NodeState
TunnelGateway1 -> Tunnel --++: broadcast NodeState(NodeID1)

Tunnel -> Tunnel : store NodeID1 TunnelGateway
note left: We store the first TunnelGateway we see the NodeID on\nWe also store the last time we saw a message from NodeID

Tunnel -> Tunnel : filter unique broadcast NodeState(NodeID1)
Tunnel -> Tunnel ++ #gold : encapsulate broadcast NodeState(NodeID1)
Tunnel -> TunnelGateway2 --++ #gold : decapsulate and broadcast NodeState(NodeID1)
deactivate Tunnel

TunnelGateway2 -> TunnelGateway2 : create/retrieve RemoteNodeSurrogate for NodeID1
note left: RemoteNodeSurrogate is a proxy for the NodeID, with broadcast and unicast endpoints
TunnelGateway2 -> TunnelGateway2 : append measurement endpoint from RemoteNodeSurrogate to NodeState
TunnelGateway2 -> LAN2 --++ #gold : broadcast PeerState(NodeID1)

actor AbletonLink2
LAN2 -> AbletonLink2 --++ #gold : receive PeerState(NodeID1)

AbletonLink2 --> LAN2 --++ #gold : unicast PeerState(NodeID2)
LAN2 --> TunnelGateway2 --++ #gold : receive PeerState(NodeID2) at UdpEndpoint for NodeID1
TunnelGateway2 --> TunnelGateway2 : lookup NodeID1 for UdpEndpoint
TunnelGateway2 --> TunnelGateway2 : store NodeID2 UdpEndpoint
TunnelGateway2 --> TunnelGateway2 : remove measurement UdpEndpoint from PeerState message, leave NodeState
TunnelGateway2 --> Tunnel --++ #gold: unicast NodeState(NodeID2) to NodeID1

Tunnel --> Tunnel : store NodeID2 TunnelGateway
Tunnel --> Tunnel : filter unique NodeState(NodeID2) to NodeID1
Tunnel --> Tunnel ++ : encapsulate unicast NodeState(NodeID2) to NodeID1
Tunnel --> Tunnel : decapsulate NodeState(NodeID2) to NodeID1
Tunnel --> Tunnel : find TunnelGateway for NodeID1
Tunnel --> TunnelGateway1 --++ : send unicast NodeState(NodeID2) to NodeID1
deactivate Tunnel

TunnelGateway1 --> TunnelGateway1 : find Endpoint for NodeID1
TunnelGateway1 --> TunnelGateway1 : create/retrieve RemoteNodeSurrogate for NodeID2
TunnelGateway1 --> TunnelGateway1 : append measurement endpoint from RemoteNodeSurrogate to NodeState
TunnelGateway1 --> LAN --++ : unicast PeerState(NodeID2) to NodeID1
LAN --> AbletonLink1 -- : receive PeerState(NodeID2)

@enduml
